apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-mainspring
namePrefix: development-
commonLabels:
  environment: development
resources:
  - ../base
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: dev
      - op: replace
        path: /spec/template/spec/containers/0/env/01/value
        value: dev
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/items/0/path
        value: application-dev.yml
    target: 
      group: apps
      version: v1
      kind: Deployment
patchesStrategicMerge:
  - mapping.yaml
  - secret.yaml
configMapGenerator:
- name: -config
  files:
  - application.yml
images:
  - name: mainspring
    newName: 684717675262.dkr.ecr.ap-south-1.amazonaws.com/mainspring
    newTag: production-tag