apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: base-base_default
namePrefix: mainspring
commonLabels:
  k8s-app: mainspring
resources:
  - deployment.yaml
  - service.yaml
  - mapping.yaml
  - secret.yaml
  - service-account.yaml
  - configmap.yaml
configurations:
- mapping-config.yaml
vars:
- name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: -service
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    name: -service
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
- name: SERVICE_ACCOUNT_NAME
  objref:
    kind: ServiceAccount
    name: -sa
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name