apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: -mapping
spec:
  bypass_auth: true
  host: <Host header>
  prefix: <API prefix>
  service: $(SERVICE_NAME).$(SERVICE_NAMESPACE):80
  timeout_ms: 10000